# Generated by Django 5.2 on 2025-09-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0003_productinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Množstvo suroviny potrebné pre výrobok', max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_products', to='angelapp.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='angelapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_m2m',
            field=models.ManyToManyField(related_name='used_in', through='angelapp.ProductIngredient', to='angelapp.product'),
        ),
    ]
