# Generated by Django 5.2 on 2025-09-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0005_alter_productingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Slovensko', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_legal_entity', models.BooleanField(default=True)),
                ('internet_id', models.CharField(max_length=50, unique=True)),
                ('ico', models.CharField(blank=True, max_length=12, null=True)),
                ('dic', models.CharField(blank=True, max_length=15, null=True)),
                ('ic_dph', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('delivery_address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='angelapp.city')),
                ('delivery_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_companies', to='angelapp.city')),
            ],
        ),
    ]
