# Generated by Django 5.2 on 2025-09-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0006_city_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
