# Generated by Django 5.2 on 2025-09-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0007_alter_city_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=100),
        ),
    ]
