# Generated by Django 5.2 on 2025-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0009_company_custom_city_name_company_custom_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='custom_postal_code',
            new_name='delivery_postal_code',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='delivery_custom_postal_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='custom_city_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='delivery_custom_city_name',
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
