# Generated by Django 5.2 on 2025-09-29 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0010_rename_custom_postal_code_company_delivery_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Čaká sa'), ('processing', 'Spracováva sa'), ('completed', 'Dokončená'), ('canceled', 'Zrušená')], default='pending', max_length=20)),
                ('created_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoCreated', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='angelapp.company')),
                ('edited_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoEdited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='angelapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='angelapp.product')),
            ],
        ),
    ]
