# Generated by Django 5.2 on 2025-10-09 09:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0014_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_on_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), max_digits=5),
        ),
    ]
