# Generated by Django 5.2 on 2025-10-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0015_product_minimum_on_stock_product_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_expedited',
            field=models.BooleanField(default=False),
        ),
    ]
