# Generated by Django 5.2 on 2025-10-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0016_orderitem_is_expedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='status',
            field=models.CharField(choices=[('manufactured', 'Vyrobené'), ('assigned', 'Priradene'), ('inspected', 'Skontrolovane'), ('defective', 'Chybný'), ('shipped', 'Expedovane')], default='priradene', max_length=50),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='angelapp.product')),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='angelapp.productinstance')),
            ],
        ),
    ]
