# Generated by Django 5.2 on 2025-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0017_productinstance_status_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('in_production', 'Vo výrobe'), ('completed', 'Dokončené'), ('canceled', 'Zrušené')], default='pending', max_length=20),
        ),
    ]
