# Generated by Django 5.2 on 2025-10-10 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0018_order_delivery_date_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('produced_quantity', models.PositiveIntegerField(default=0)),
                ('defective_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Čaká sa'), ('in_production', 'Vo výrobe'), ('completed', 'Dokončené'), ('canceled', 'Zrušené')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock_receipt_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_cards', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='production_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='angelapp.productioncard'),
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(max_length=50, unique=True)),
                ('plan_type', models.CharField(choices=[('monthly', 'Mesačný'), ('weekly', 'Týždenný')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('planned_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Čaká sa'), ('in_production', 'Vo výrobe'), ('partially completed', 'Čiastočne dokončená'), ('completed', 'Dokončené'), ('canceled', 'Zrušené')], default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plan_items', to='angelapp.product')),
                ('production_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_item_relation', to='angelapp.productioncard')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='angelapp.productionplan')),
            ],
        ),
        migrations.AddField(
            model_name='productioncard',
            name='plan_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_card_relation', to='angelapp.productionplanitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_plan_items',
            field=models.ManyToManyField(blank=True, to='angelapp.productionplanitem'),
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to='angelapp.product')),
                ('production_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts', to='angelapp.productioncard')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts', to='angelapp.productionplan')),
            ],
        ),
    ]
