# Generated by Django 5.2 on 2025-10-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0019_order_note_productioncard_orderitem_production_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplanitem',
            name='prenesene_ks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
