# Generated by Django 5.2 on 2025-10-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0020_productionplanitem_prenesene_ks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionplanitem',
            old_name='prenesene_ks',
            new_name='transfered_pc',
        ),
    ]
