# Generated by Django 5.2 on 2025-10-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0021_rename_prenesene_ks_productionplanitem_transfered_pc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionplanitem',
            old_name='transfered_pc',
            new_name='transfered_pcs',
        ),
    ]
