# Generated by Django 5.2 on 2025-10-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0022_rename_transfered_pc_productionplanitem_transfered_pcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncard',
            name='plan_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_cards', to='angelapp.productionplanitem'),
        ),
    ]
