# Generated by Django 5.2 on 2025-11-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0023_alter_productioncard_plan_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplanitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('in_production', 'Vo výrobe'), ('partially completed', 'Čiastočne prenesená'), ('completed', 'Dokončené'), ('canceled', 'Zrušené')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='receipt_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
