# Generated by Django 5.2 on 2025-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0024_alter_productionplanitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncard',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('in_production', 'Vo výrobe'), ('partially_completed', 'Čiastočne dokončené'), ('completed', 'Dokončené'), ('canceled', 'Zrušené')], default='pending', max_length=20),
        ),
    ]
