# Generated by Django 5.2 on 2025-12-13 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0025_alter_productioncard_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_issues_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_issues', to='angelapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='StockIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='angelapp.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='angelapp.product')),
                ('stock_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='angelapp.stockissue')),
            ],
        ),
        migrations.CreateModel(
            name='StockIssueInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='angelapp.productinstance')),
                ('stock_issue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='angelapp.stockissueitem')),
            ],
        ),
    ]
