# Generated by Django 5.2 on 2025-12-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0026_stockissue_stockissueitem_stockissueinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='status',
            field=models.CharField(default='issued', max_length=20),
        ),
    ]
