# Generated by Django 5.2 on 2025-12-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0027_producttype_code_alter_stockissue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockissue',
            name='is_storno',
            field=models.BooleanField(default=False),
        ),
    ]
