# Generated by Django 5.2 on 2025-12-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0028_stockissue_is_storno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockissueitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_issue_items', to='angelapp.orderitem'),
        ),
    ]
