# Generated by Django 5.2 on 2025-12-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0029_alter_stockissueitem_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('processing', 'Spracováva sa'), ('partially completed', 'Čiastocne prenesená'), ('completed', 'Dokončená'), ('canceled', 'Zrušená')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('in_production', 'Vo výrobe'), ('partially completed', 'Čiastočne prenesená'), ('completed', 'Dokončené'), ('canceled', 'Zrušené')], default='pending', max_length=30),
        ),
    ]
