# Generated by Django 5.2 on 2025-12-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0030_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(choices=[('manufactured', 'Vyrobené'), ('assigned', 'Priradene'), ('inspected', 'Skontrolovane'), ('defective', 'Chybný'), ('shipped', 'Expedovane')], default='assigned', max_length=50),
        ),
    ]
