# Generated by Django 5.2 on 2025-12-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0031_alter_productinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(choices=[('manufactured', 'Vyrobené'), ('assigned', 'Priradene'), ('inspected', 'Skontrolovane'), ('defective', 'Chybný'), ('shipped', 'Expedovane')], default='manufactured', max_length=50),
        ),
    ]
