# Generated by Django 5.2 on 2025-12-18 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0032_alter_productinstance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_date', models.DateField(verbose_name='Dátum výroby')),
                ('visual_check', models.BooleanField(default=False, verbose_name='Vizuálna kontrola')),
                ('packaging_check', models.BooleanField(default=False, verbose_name='Kontrola balenia')),
                ('defect_status', models.CharField(choices=[('ok', 'Bez chyby'), ('error', 'Chyba')], default='ok', max_length=10, verbose_name='Status chybovosti')),
                ('defect_description', models.TextField(blank=True, null=True, verbose_name='Popis chyby')),
                ('checked_at', models.DateField(auto_now_add=True, verbose_name='Dátum kontroly')),
                ('approved_for_shipping', models.BooleanField(default=False, verbose_name='Povolené k expedícii')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checked_quality_items', to=settings.AUTH_USER_MODEL, verbose_name='Kontroloval')),
                ('manufactured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufactured_quality_items', to=settings.AUTH_USER_MODEL, verbose_name='Vyrobil')),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='angelapp.productinstance', verbose_name='Kus produktu')),
            ],
        ),
    ]
