# Generated by Django 5.2 on 2025-12-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0033_itemqualitycheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemqualitycheck',
            name='product_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quality_check', to='angelapp.productinstance', verbose_name='Kus produktu'),
        ),
    ]
