# Generated by Django 5.2 on 2025-12-18 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0034_alter_itemqualitycheck_product_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rozpracovaná'), ('ready', 'Pripravená'), ('shipped', 'Odoslaná')], default='draft', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expeditions', to='angelapp.order')),
                ('stock_issue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedition', to='angelapp.stockissue')),
            ],
        ),
        migrations.CreateModel(
            name='ExpeditionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='angelapp.expedition')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='angelapp.orderitem')),
                ('product_instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expedition_item', to='angelapp.productinstance')),
                ('stock_issue_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='angelapp.stockissueitem')),
            ],
        ),
    ]
