# Generated by Django 5.2 on 2025-12-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0035_expedition_expeditionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expeditionitem',
            name='product_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedition_item', to='angelapp.productinstance'),
        ),
    ]
