# Generated by Django 5.2 on 2025-12-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0036_alter_expeditionitem_product_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('in_production', 'Vo výrobe'), ('partially_completed', 'Čiastočne prenesená'), ('completed', 'Dokončené'), ('canceled', 'Zrušené')], default='pending', max_length=30),
        ),
    ]
