# Generated by Django 5.2.9 on 2025-12-29 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0037_expeditionitem_quantity_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='edited_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('processing', 'Spracováva sa'), ('partially_completed', 'Čiastocne prenesená'), ('completed', 'Dokončená'), ('canceled', 'Zrušená')], default='pending', max_length=20),
        ),
    ]
