# Generated by Django 5.2 on 2025-12-30 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0038_alter_order_created_at_alter_order_created_who_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockissueitem',
            name='expedition_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_issue_items', to='angelapp.expeditionitem'),
        ),
    ]
