# Generated by Django 5.2 on 2026-01-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0039_stockissueitem_expedition_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='expedition_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
